import type { ID } from "../types";

export const queryKeys = {
  profile: ["profile"] as const,
  publicInstance: ["publicInstance"] as const,
  instanceCapabilities: ["instanceCapabilities"] as const,
  oauthProviders: ["oauthProviders"] as const,
  projects: ["projects"] as const,
  project: (projectId: ID) => ["project", projectId] as const,
  projectRoles: (projectId: ID) => ["projectRoles", projectId] as const,
  githubRepositories: (projectId: ID) => ["githubRepositories", projectId] as const,
  projectGitHubCommitsScope: (projectId: ID) => ["projectGitHubCommits", projectId] as const,
  projectGitHubCommits: (projectId: ID, filtersKey = "all") => ["projectGitHubCommits", projectId, filtersKey] as const,
  projectMembers: (projectId: ID) => ["projectMembers", projectId] as const,
  projectInvitesScope: (projectId: ID) => ["projectInvites", projectId] as const,
  projectInvites: (projectId: ID, status?: string) => ["projectInvites", projectId, status || "all"] as const,
  myProjectInvitesScope: ["myProjectInvites"] as const,
  myProjectInvites: (status?: string) => ["myProjectInvites", status || "all"] as const,
  myRemoteProjectInvitesScope: ["myRemoteProjectInvites"] as const,
  myRemoteProjectInvites: (status?: string) => ["myRemoteProjectInvites", status || "all"] as const,
  notifications: ["notifications"] as const,
  projectDeliveries: (projectId: ID, state?: string) => ["projectDeliveries", projectId, state || "all"] as const,
  projectDeliverySummary: (projectId: ID) => ["projectDeliverySummary", projectId] as const,
  personalFederationInbox: ["personalFederationInbox"] as const,
  personalFederationFollowsScope: ["personalFederationFollows"] as const,
  personalFederationFollows: (state?: string) => ["personalFederationFollows", state || "all"] as const,
  tickets: (projectId: ID) => ["tickets", projectId] as const,
  ticket: (ticketId: ID) => ["ticket", ticketId] as const,
  ticketGitHubCommitsScope: ["ticketGitHubCommits"] as const,
  ticketGitHubCommits: (ticketId: ID) => ["ticketGitHubCommits", ticketId] as const,
  comments: (ticketId: ID) => ["comments", ticketId] as const,
  graphScope: (projectId: ID) => ["graph", projectId] as const,
  graph: (projectId: ID, filtersKey = "default") => ["graph", projectId, filtersKey] as const,
  adminUsers: (role?: string, q?: string) => ["adminUsers", role || "all", q || ""] as const,
  adminAuditEvents: (action?: string, targetType?: string, actorUserId?: string) =>
    ["adminAuditEvents", action || "all", targetType || "all", actorUserId || ""] as const,
  federationDomainBlocks: ["federationDomainBlocks"] as const,
  federationRemoteActors: (fetchError?: string) => ["federationRemoteActors", fetchError || "all"] as const,
  federationDeliveries: (state?: string, failureKind?: string) =>
    ["federationDeliveries", state || "all", failureKind || "all"] as const,
  federationDeliverySummary: ["federationDeliverySummary"] as const,
};
